spring.application.name=musicas-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${MUSICAS_DB_HOST:localhost}:5432/${MUSICAS_DB_NAME:musicas_db}
spring.datasource.username=${MUSICAS_DB_USER:usuario}
spring.datasource.password=${MUSICAS_DB_PASSWORD:senha}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
jogos.service.url=${JOGOS_SERVICE_URL:http://localhost:8080}