spring.application.name=enlistamento-service
server.port=8083

spring.datasource.url=jdbc:postgresql://${ENLISTAMENTO_DB_HOST:localhost}:5432/${ENLISTAMENTO_DB_NAME:enlistamento_db}
spring.datasource.username=${ENLISTAMENTO_DB_USER:usuario}
spring.datasource.password=${ENLISTAMENTO_DB_PASSWORD:senha}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
jogos.service.url=${JOGOS_SERVICE_URL:http://localhost:8080}